# Generated by Django 3.2.18 on 2023-07-27 02:46

from django.db import migrations, models
import geocollections.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Geocollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geojson_data', models.JSONField(blank=True, null=True)),
                ('category', models.CharField(choices=[('cooperatives', 'Cooperatives'), ('forest-offices', 'Forest Offices'), ('health-institutions', 'Health Institutions'), ('municipal-offices', 'Municipal Offices'), ('religious-places', 'Religious Places'), ('schools', 'Schools'), ('security-offices', 'Security Offices'), ('tourism', 'Tourism'), ('others', 'Others')], max_length=50, null=True)),
                ('image_folder', models.FileField(blank=True, null=True, upload_to=geocollections.models.get_image_folder)),
                ('zip_file', models.FileField(blank=True, null=True, upload_to='zip_files/')),
            ],
        ),
        migrations.CreateModel(
            name='SHPtoGeojson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shp_geojson_data', models.JSONField(null=True)),
            ],
        ),
    ]
