# Generated by Django 3.2.18 on 2023-07-16 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocollections', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geocollection',
            name='group',
        ),
        migrations.RemoveField(
            model_name='geocollection',
            name='name',
        ),
        migrations.RemoveField(
            model_name='geocollection',
            name='resources',
        ),
        migrations.RemoveField(
            model_name='geocollection',
            name='slug',
        ),
        migrations.AddField(
            model_name='geocollection',
            name='geojson_file',
            field=models.FileField(blank=True, null=True, upload_to='static/Geocollections/DataSets/geojson/'),
        ),
    ]
