# Generated by Django 3.2.18 on 2023-07-16 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocollections', '0002_auto_20230716_0155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geocollection',
            name='geojson_file',
        ),
        migrations.AddField(
            model_name='geocollection',
            name='geojson_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
