# Generated by Django 3.2.18 on 2023-07-21 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocollections', '0005_auto_20230717_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geocollection',
            name='category',
            field=models.CharField(choices=[('cooperatives', 'Cooperatives'), ('forest-offices', 'Forest Offices'), ('health-institutions', 'Health Institutions'), ('municipal-offices', 'Municipal Offices'), ('religious-places', 'Religious Places'), ('schools', 'Schools'), ('security-offices', 'Security Offices'), ('tourism', 'Tourism'), ('others', 'Others')], max_length=50, null=True),
        ),
    ]
