# Generated by Django 3.2.18 on 2023-07-23 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocollections', '0006_alter_geocollection_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='SHPtoGeojson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geojson_data', models.JSONField()),
            ],
        ),
    ]
